#[tool.poetry]
#name = "ggutils"
#version = "0.1.0"
#description = "A simple function library used in my Gamma Gear project."
#authors = ["Yormi8"]
#
#[tool.poetry.dependencies]
#python = ">= 3.11.0, < 3.13.0"
#wiztype = "^0.1.8"
#regex = "2023.8.8"
#katsuba = { git = "https://github.com/vbe0201/katsuba.git", tag = "v0.8.4", subdirectory = "src/katsuba-py" }
#
#[build-system]
#requires = ["poetry-core"]
#build-backend = "poetry.core.masonry.api"

[project]
name = "ggutils"
version = "0.1.0"
description = "A simple function library used in my Gamma Gear project."
authors = [ { name = "Yormi8" } ]
requires-python = ">=3.11.0, <3.13.0"
dependencies = [
    "wiztype ~= 0.1.8",
    "regex == 2023.8.8",
    "katsuba @ git+ssh://git@github.com/vbe0201/katsuba.git@74042051df174034d23b2b72b871689c27d3fdcc#subdirectory=src/katsuba-py"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
